server:
  servlet:
    context-path: /advogasystem/api

springdoc:
  swagger-ui:
    path: /swagger

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb+srv://dev:root@desenvolvimento.alcvqf1.mongodb.net/desenvolvimento?retryWrites=true&w=majority&appName=Desenvolvimento}
      auto-index-creation: true