server:
  servlet:
    context-path: /advogasystem/api

springdoc:
  swagger-ui:
    path: /public/swagger

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb+srv://dev:root@desenvolvimento.alcvqf1.mongodb.net/desenvolvimento?retryWrites=true&w=majority&appName=Desenvolvimento}
      auto-index-creation: true

advogasystem:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:120}
    chave: ${JWT_CHAVE:123456}